name: Version Tag

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'
    - name: Install dependencies
      run: |
        pip install --editable .
        pip install packaging
    - name: Fetch version
      run: |
        latest_version=$(pip show project_extraction | awk '/^Version: / {sub("^Version: ", ""); print}')
        echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV
    - name: Push tag
      run: |
        git tag -a "$LATEST_VERSION" HEAD -m "Version v$LATEST_VERSION"
        git push origin "$LATEST_VERSION"
