name: Version Check

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and check version
      run: |
        git fetch --tags
        python setup.py sdist bdist_wheel
        current=$(git describe --tags --match="[0-9]*" HEAD)
        new=$(pip show ibllib | awk '/^Version: / {sub("^Version: ", ""); print}')
        python <<EOP
        import sys; from packaging import version
        sys.exit(int(version.parse("$current") >= version.parse("$new")))
        EOP
        RC=$?
        echo "Exit code $RC"
    - name: Push tag
      run: |
        git tag -a "$new" HEAD
        git push origin "$new"
